In [3]:
import numpy as np
import pandas as pd

In [4]:
def calcNewResult1(circuit):
    x  = len(circuit)
    B = []
    s = ""
    qubit_state = []
    for i in reversed(range(x)):
        s+= circuit[i][0]

    qubit_state = states(s)
    Hgate = 1/np.sqrt(2) * np.array([[1.0,1.0],[1.0,-1.0]])
    Xgate = np.array([[0.0,1.0],[1.0,0.0]])
    Zgate = np.array([[1.0,0.0],[0.0,-1.0]])
    Ygate = np.array([[0.0,-1j],[1j,0.0]])
    IDgate = np.array([[1.0,0.0],[0.0,1.0]])
    Cnot = np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
    Cnot1 = np.array([[1,0,0,0],[0,0,0,1],[0,0,1,0],[0,1,0,0]])
    
    for i in range(max(map(lambda x: len (x), circuit))):
        if(i>0):
            
            for k in range(len(circuit)):
                if(circuit[k][i] == 'H'):
                    B.append(Hgate)
                elif(circuit[k][i] == 'X'):
                    if(circuit[k-1][i] == "N" and circuit[k][i] == 'X'):
                        B.append(Cnot)
                        continue
                    else:
                        B.append(Xgate) 
                elif(circuit[k][i] == 'Y'):
                    B.append(Ygate) 
                elif(circuit[k][i] == 'Z'):
                    B.append(Zgate) 
                elif(circuit[k][i] == 'I' or circuit[k][i] == '/'):#or circuit[k][i] == 'N'): 
                    B.append(IDgate)
                elif(circuit[k][i] == 'N'):
                    if(circuit[k-1][i] == "X" and circuit[k][i] == 'N'):
                        B.append(Cnot1)
                        continue
                    else:
                        B.append(IDgate)
    for i in range(0,len(B),2):
            qubit_state = Estim2(qubit_state,B[i],B[i+1])
    result = qubit_state.tolist()
    return result
def states(s):
        q=[]
        if(s == '0'):
            q = [1,0]
        if(s == '1'):
            q = [0,1]
        if(s == '00'):
            q = [1,0,0,0]
        if(s == '01'):
            q = [0,1,0,0]
        if(s == '10'):
            q = [0,0,1,0]
        if(s == '11'):
            q = [0,0,0,1]
        return q
def Estim2(q,gate1,gate2):
        print(len(gate1),len(gate2))
        D = []
        E = []
        print("q",q,"gate1",gate1,"gate12",gate2)
        if(len(gate1) == 2 and len(gate2) == 2):
            E = np.kron(gate2,gate1)
            D = np.dot(E,q)
        elif(len(gate1) == 4):
            D = np.dot(gate1,q)
       
        return D

In [5]:
#calcNewResult1([['0', 'H', 'N'], ['0', 'I', 'X']])
#calcNewResult1([['0', 'I', 'X'], ['0', 'H', 'N']])
#calcNewResult1([['0', 'X', 'N'], ['0', 'I', 'X']])
#calcNewResult1([['0', 'I', 'X'], ['0', 'X', 'N']])
calcNewResult1([['0', 'H', 'N', '/', '/', '/'], ['0', 'I', 'X', '/', '/', '/']])

2 2
q [1, 0, 0, 0] gate1 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]] gate12 [[1. 0.]
 [0. 1.]]
4 4
q [0.70710678 0.70710678 0.         0.        ] gate1 [[1 0 0 0]
 [0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]] gate12 [[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]
2 2
q [0.70710678 0.         0.         0.70710678] gate1 [[1. 0.]
 [0. 1.]] gate12 [[1. 0.]
 [0. 1.]]
2 2
q [0.70710678 0.         0.         0.70710678] gate1 [[1. 0.]
 [0. 1.]] gate12 [[1. 0.]
 [0. 1.]]
2 2
q [0.70710678 0.         0.         0.70710678] gate1 [[1. 0.]
 [0. 1.]] gate12 [[1. 0.]
 [0. 1.]]


[0.7071067811865475, 0.0, 0.0, 0.7071067811865475]

In [ ]:
if(len(gate1) == 2 and len(gate2) == 2 or np.array_equal(gate2,IDgate)):
                #print("I am here gate1")
                E = np.kron(gate2,gate1)
                D = np.dot(E,q)
                print("D",D)
        elif(len(gate1) == 2 and len(gate2) == 2 or np.array_equal(gate1,IDgate)):
                #print("I am here gate2")
                E = np.kron(gate1,gate2)
                D = np.dot(E,q)
                print("D",D)
        elif(len(gate1) == 4 or len(gate2) == 4):
            if(len(gate1) == 4):
                #print("I am here 2")
                D = np.dot(gate2,q)
                print("D",D)
            elif(len(gate2) == 4):
                #print("I am here 3")
                D = np.dot(gate1,q)
                print("D",D)